updated version to 1.5, hacked get_version for now

diff --git a/scripts/release/get_version b/scripts/release/get_version
--- a/scripts/release/get_version
+++ b/scripts/release/get_version
@@ -4,12 +4,15 @@ pwiz_root=$(dirname $0)/../..
 pushd $pwiz_root > /dev/null
 
 # parse version string from pwiz/Version.cpp Version::str() implementation
-version_string=$(cat pwiz/Version.cpp | grep 'Version::str()' | awk -F\" '{print $2}')
-if [ $? -ne 0 ]
-then
-    echo "Error getting version string."
-    return 1
-fi
+#version_string=$(cat pwiz/Version.cpp | grep 'Version::str()' | awk -F\" '{print $2}')
+#if [ $? -ne 0 ]
+#then
+#    echo "Error getting version string."
+#    return 1
+#fi
+
+# hack -- do this right!
+version_string=1.5.0
 
 echo $version_string
 
